name: Linting
on:
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-22.04 # See https://github.com/errata-ai/vale-action/issues/128 before upgrading
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        version: 2.29.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip3 install -r docs/requirements.txt
    
    - name: Build docs
      working-directory: docs
      run: make html

    - name: Check links
      working-directory: docs
      run: make checklinks

  doctor_rst:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create cache dir
      run: mkdir .cache

    - name: Extract base branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_BASE_REF:=${GITHUB_REF##*/}})"
      id: extract_base_branch

    - name: Get Changed Files
      id: changes
      run: |
        echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '^docs/' | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Cache DOCtor-RST
      uses: actions/cache@v2
      with:
        path: .cache
        key: doctor-rst-${{ runner.os }}-${{ steps.extract_base_branch.outputs.branch }}
        restore-keys: |
          doctor-rst-${{ runner.os }}-
          doctor-rst-

    - name: Run DOCtor-RST
      if: env.CHANGED_FILES != ''
      uses: docker://oskarstark/doctor-rst
      with:
        args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache ${{ env.CHANGED_FILES }}
      env:
        DOCS_DIR: 'docs/'
